backend/bracket/routes/auth.py
backend/bracket/routes/clubs.py
backend/bracket/routes/users.py
backend/bracket/sql/users.py
backend/tests/integration_tests/api/clubs_test.py
backend/tests/integration_tests/api/matches_test.py
backend/tests/integration_tests/api/players_test.py
backend/tests/integration_tests/api/shared.py
backend/tests/integration_tests/api/teams_test.py
backend/tests/integration_tests/api/tournaments_test.py
backend/tests/integration_tests/api/users_test.py

Adds various integration tests for users, tournaments and upcoming matches.

Add integration tests for users

---

backend/Pipfile

To prevent this error: https://github.com/evroon/bracket/actions/runs/5374165121/jobs/9884686569

Update mypy requirement

---

frontend/src/components/navbar/_brand.tsx
frontend/src/pages/_layout.tsx
frontend/src/pages/tournaments/_tournament_layout.tsx

Fixes this issue:
Still more work is indeed to make the admin part fully responsive.

Improve responsiveness header

---

backend/bracket/sql/clubs.py
frontend/src/components/scheduling/scheduling.tsx
frontend/src/components/tables/clubs.tsx
frontend/src/components/tables/players.tsx
frontend/src/components/tables/stages.tsx
frontend/src/components/tables/teams.tsx
frontend/src/components/tables/tournaments.tsx
frontend/src/components/tables/upcoming_matches.tsx
frontend/src/components/utils/empty_table_info.tsx

Add alerts for tables without rows and fix SQL bugs in backend.

Backend bugfixes and frontend fixes

---

frontend/src/pages/login.tsx
frontend/src/services/adapter.tsx
frontend/src/services/local_storage.tsx

Fixes the issue where you have to login twice to pass the login screen.

Fix login handling

---

README.md
backend/Dockerfile
backend/bracket/app.py
backend/bracket/config.py
backend/bracket/database.py
backend/bracket/routes/auth.py
backend/bracket/sql/users.py
backend/bracket/utils/db_init.py
backend/cli.py
backend/run.sh
codecov.yml
docker-compose.yml
frontend/.dockerignore
frontend/Dockerfile

part of https://github.com/evroon/bracket/issues/197
Adds docker-compose.yml and makes bracket suitable to be run in Docker.

Add docker compose config

---

frontend/src/services/user.tsx

`data` is not assigned anything, so this would result in problems as described here: 
https://github.com/evroon/bracket/issues/197#issuecomment-1732550489

Fix login error handling

---

backend/bracket/models/db/player.py
backend/bracket/models/db/team.py
backend/bracket/routes/players.py
backend/bracket/routes/teams.py
backend/tests/integration_tests/api/players_test.py
backend/tests/integration_tests/api/teams_test.py
frontend/src/components/buttons/save.tsx
frontend/src/components/forms/player_create_csv_input.tsx
frontend/src/components/modals/player_create_modal.tsx
frontend/src/components/modals/player_update_modal.tsx
frontend/src/components/modals/spotlight.tsx
frontend/src/components/modals/team_create_modal.tsx
frontend/src/components/modals/team_update_modal.tsx
frontend/src/components/tables/players.tsx
frontend/src/components/tables/teams.tsx
frontend/src/pages/tournaments/[id]/players.tsx
frontend/src/pages/tournaments/[id]/teams.tsx
frontend/src/services/player.tsx
frontend/src/services/team.tsx

fixes https://github.com/evroon/bracket/issues/292

Multi users and teams creation

---

backend/bracket/logic/ranking/elo.py
frontend/src/components/modals/tournament_modal.tsx
frontend/src/components/tables/standings.tsx
frontend/src/pages/tournaments/[id]/settings.tsx
frontend/src/services/tournament.tsx

Some fields were missing in the form to create tournaments

Fix tournament creation

---

frontend/src/components/brackets/brackets.tsx
frontend/src/components/brackets/courts.tsx
frontend/src/components/brackets/round.tsx
frontend/src/components/builder/builder.tsx
frontend/src/components/tables/standings.tsx
frontend/src/components/tables/table.tsx
frontend/src/services/lookups.tsx

Apparently this worked on firefox but not chromium-based browsers
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#parameters

Fix array sorting

---

frontend/src/components/modals/create_stage_item.tsx

fixes https://github.com/evroon/bracket/issues/380

Fix stage item modal: team_id should be string

---

backend/bracket/cronjobs/scheduling.py
backend/bracket/sql/users.py
backend/bracket/utils/db_init.py
backend/tests/integration_tests/api/conftest.py
backend/tests/integration_tests/conftest.py
backend/tests/integration_tests/db_init_test.py
codecov.yml

fixes https://github.com/evroon/bracket/issues/426

Fix db initialisation

---

backend/bracket/app.py
backend/bracket/sql/users.py
backend/tests/integration_tests/api/auth_test.py
backend/tests/integration_tests/api/users_test.py
backend/tests/integration_tests/conftest.py
backend/tests/integration_tests/cronjobs/demo_user_deletion_test.py
backend/tests/integration_tests/mocks.py

Fixes error due to `._mapping` invalid return type

Fix demo account deletion

---

.github/workflows/contributors.yml
README.md
docs/docs/community/contributing.md

and in docs as well
also includes github action for automatic updates

Contributors in readme

---

backend/bracket/app.py
backend/bracket/config.py
backend/bracket/logic/planning/matches.py
backend/bracket/logic/scheduling/builder.py
backend/bracket/logic/scheduling/elimination.py
backend/bracket/logic/scheduling/round_robin.py
backend/bracket/logic/scheduling/upcoming_matches.py
backend/bracket/models/db/round.py
backend/bracket/routes/matches.py
backend/bracket/routes/rounds.py
backend/bracket/routes/stage_items.py
backend/bracket/sql/rounds.py
backend/tests/integration_tests/api/auto_scheduling_matches_test.py
backend/tests/integration_tests/api/users_test.py
backend/tests/integration_tests/conftest.py

Remove unused code and add some tests
Also fix detection of running pytest

Increase code coverage

---

backend/bracket/routes/models.py
backend/bracket/routes/players.py
backend/bracket/routes/teams.py
backend/bracket/sql/players.py
backend/bracket/sql/teams.py
backend/bracket/utils/pagination.py
backend/tests/integration_tests/api/players_test.py
backend/tests/integration_tests/api/teams_test.py
frontend/src/components/modals/team_create_modal.tsx
frontend/src/components/modals/team_update_modal.tsx
frontend/src/components/tables/players.tsx
frontend/src/components/tables/standings.tsx
frontend/src/components/utils/util.tsx
frontend/src/pages/tournaments/[id]/players.tsx
frontend/src/pages/tournaments/[id]/teams.tsx
frontend/src/services/adapter.tsx
frontend/src/services/lookups.tsx

Adds pagination (backend and frontend) to teams and players GET endpoints

Add pagination

---

frontend/src/pages/tournaments/[id].tsx
frontend/src/pages/tournaments/[id]/courts.tsx
frontend/src/pages/tournaments/[id]/settings.tsx
frontend/src/pages/tournaments/[id]/stages.tsx
frontend/src/pages/tournaments/_tournament_layout.tsx
frontend/src/services/adapter.tsx

This PR simplifies fetching of a single tournament

Improve fetching of tournaments

---

backend/bracket/routes/tournaments.py
backend/bracket/sql/tournaments.py

fix https://github.com/evroon/bracket/issues/514

Use asyncpg for updating tournaments

---

docs/docusaurus.config.js

Some values were not set correctly

Fix docusaurus config

---

frontend/Dockerfile

Dockerfile fix

---

backend/Dockerfile

Support for multiple is still WIP

Spawn only 1 gunicorn worker for now

---

frontend/package.json
frontend/yarn.lock

To fix CI
This reverts commit bb17b99a88c4961c0cbf68ad2a9a10ddde4dfaca.

Revert "Bump @next/eslint-plugin-next from 14.0.4 to 14.1.2

---

docker-compose.yml
docs/docs/deployment/docker.md

fixes https://github.com/evroon/bracket/issues/518

Add static volume to docker docs

---

frontend/src/components/modals/create_stage_item.tsx
frontend/src/components/modals/update_stage.tsx
frontend/src/components/modals/update_stage_item.tsx
frontend/src/components/scheduling/scheduling.tsx
frontend/src/components/tables/upcoming_matches.tsx
frontend/src/interfaces/stage.tsx
frontend/src/pages/tournaments/[id].tsx
frontend/src/services/adapter.tsx

This fixes a few small bugs related to upcoming matches for swiss

Fix upcoming matches table

---

backend/bracket/routes/stage_items.py
backend/bracket/utils/errors.py
frontend/src/components/forms/user.tsx

fix https://github.com/evroon/bracket/issues/629

Handle foreign key on stage items

---

backend/bracket/app.py

This actually made the CORS handling more strict...

Revert attempt to disable cors

---

docs/docs/usage/_category_.json
docs/docs/usage/introduction.md
docs/docs/usage/terminology.md
process-compose-example.yml

fixes https://github.com/evroon/bracket/issues/415

Add usage guide and terminology page

---

frontend/src/components/utils/datetime.tsx
frontend/src/pages/tournaments/[id]/dashboard/index.tsx

fixes https://github.com/evroon/bracket/issues/979
also reverses the order so it is now in ascending order from oldest to most recent match.

Fix sorting of matches on dashboard

---

docs/content/community/contributing.mdx

I would prefer to keep it here as well, but the GH action doesn't support mdx files so this section has been broken

Link to README for contributers

---

.github/workflows/contributors.yml

GH Action doesn't seem to work for mdx files

Remove job from GH action contributors.yml
