- backend/bracket/routes/matches.py
- backend/bracket/routes/models.py
- backend/bracket/sql/matches.py
- backend/bracket/utils/dummy_records.py
- backend/pyproject.toml
- backend/tests/integration_tests/api/conftest.py
- backend/tests/integration_tests/api/matches_test.py
- backend/tests/integration_tests/api/players_test.py
- backend/tests/integration_tests/api/rounds_test.py
- backend/tests/integration_tests/api/stages_test.py
- backend/tests/integration_tests/api/teams_test.py
- backend/tests/integration_tests/api/tournaments_test.py
- backend/tests/integration_tests/api/users_test.py
- backend/tests/integration_tests/mocks.py
- backend/tests/integration_tests/sql.py
> Stop using fixed db ids in tests

- README.md
- docker-compose.yml
Adds a quickstart section to README explaining how to run Bracket with docker-compose.
See https://github.com/evroon/bracket/issues/197
> Add docker compose instructions

- .github/workflows/backend.yml
This reverts commit 3b99b5940f0c2645494605c12aa000b34f28292b.
stable release doesn't exist yet
> Revert "Bump codecov/codecov-action from 3 to 4 (#268)"

- backend/alembic/versions/85d260b43ad4_create_tournaments_dashboard_endpoint.py
- backend/bracket/models/db/tournament.py
- backend/bracket/routes/tournaments.py
- backend/bracket/schema.py
- backend/bracket/sql/tournaments.py
- backend/bracket/utils/dummy_records.py
- backend/tests/integration_tests/api/tournaments_test.py
- frontend/src/components/modals/tournament_modal.tsx
- frontend/src/components/utils/file_upload.tsx
- frontend/src/components/utils/util.tsx
- frontend/src/interfaces/tournament.tsx
- frontend/src/pages/tournaments/[id].tsx
- frontend/src/pages/tournaments/[id]/dashboard.tsx
- frontend/src/pages/tournaments/[id]/settings.tsx
- frontend/src/services/adapter.tsx
- frontend/src/services/tournament.tsx
fixes https://github.com/evroon/bracket/issues/276
> Dashboard endpoint

- backend/bracket/logic/matches.py
- frontend/src/components/brackets/brackets.tsx
- frontend/src/components/brackets/match.tsx
- frontend/src/components/brackets/round.tsx
- frontend/src/components/scheduling/scheduling.tsx
- frontend/src/components/tables/teams.tsx
- frontend/src/components/tables/upcoming_matches.tsx
- frontend/src/interfaces/brackets.tsx
- frontend/src/interfaces/match.tsx
- frontend/src/pages/tournaments/[id].tsx
- frontend/src/pages/tournaments/[id]/dashboard/index.tsx
- frontend/src/services/lookups.tsx
> Add segmented control to filter matches

- backend/bracket/app.py
- backend/bracket/config.py
- backend/ci.env
In development, CORS isn't really useful to enable.
I added a warning in production if the `CORS_ORIGINS` env var is set to `*` (the default).
> Make cors middleware disabled by default

- backend/bracket/routes/auth.py
- backend/bracket/routes/users.py
- backend/bracket/utils/db_init.py
- backend/bracket/utils/dummy_records.py
- backend/bracket/utils/security.py
- backend/cli.py
fixes https://github.com/evroon/bracket/issues/451
Old password hashes are still valid
> Replace passlib by bcrypt

- backend/bracket/config.py
- backend/bracket/logic/planning/matches.py
Also use CI environment when running pytest
> Fix invalid order of matches in schedule

- frontend/src/components/tables/clubs.tsx
- frontend/src/components/tables/courts.tsx
- frontend/src/components/tables/players.tsx
- frontend/src/components/tables/teams.tsx
- frontend/src/components/tables/tournaments.tsx
- frontend/src/pages/tournaments/[id]/stages.tsx
- frontend/src/pages/user.tsx
Using isValidating, we see flickering in the UI because we don't use the caching of SWR optimally. We only need to check whether there is some data available, expired or not.
> Stop using isvalidating

- .gitignore
- backend/bracket/routes/tournaments.py
- backend/tests/integration_tests/api/shared.py
- backend/tests/integration_tests/api/tournaments_test.py
- frontend/public/locales/en/common.json
- frontend/public/locales/nl/common.json
- frontend/public/locales/zh-CN/common.json
- frontend/src/components/utils/file_upload.tsx
Otherwise uploads can replace current files with the same name.
Also fixes and adds more tests for logo uploads.
> Use uuids for logos

- backend/cli.py
This PR adds a custom function to be able to add users from the CLI. This is a bare-bones modification to cli.py that works, and I've semi tested (against a production environment lol). I am opening this PR as an RFC.
> Add user registration to cli

- backend/bracket/routes/matches.py
- backend/bracket/routes/rounds.py
- backend/bracket/routes/stage_items.py
- backend/bracket/routes/teams.py
- backend/bracket/routes/users.py
- backend/bracket/sql/players.py
- backend/bracket/sql/stage_items.py
- backend/bracket/sql/validation.py
- backend/pyproject.toml
- backend/tests/integration_tests/api/teams_test.py
Handles a security vulnerability where it's possible to link to columns of other tournaments, such as add players from another tournament to a team
> Check foreign keys belong to tournament

- backend/bracket/app.py
- backend/bracket/utils/alembic.py
- backend/bracket/utils/db_init.py
fix https://github.com/evroon/bracket/issues/520
After initializing the database, we don't want/need to run any migrations, so we just tell alembic we're on the latest revision.
> Stamp alembic head when recreating tables

- backend/alembic/versions/1961954c0320_fix_created_columns.py
- backend/bracket/schema.py
The default was wrong, the `"now()"` was executed when building the database, resulting in a default of a constant value instead of the function `now()`
> Fix created columns

- backend/bracket/sql/stages.py
> fix: stage selection

- backend/bracket/app.py
- backend/bracket/config.py
It's too confusing for new users and we have a warning if you disable it on production anyway.
> Disable cors by default

- .github/workflows/publish_docker_image.yml
Extend the Docker publishing workflow to build and push images for both amd64 and arm64 architectures using Docker Buildx.
> Add multi-architecture build support to GitHub Actions

- .github/workflows/publish_docker_image.yml
- README.md
- docs/docs/community/contributing.md
After many tests, I have now discovered that there is currently a problem with node and arm64 in GitHub workflows. There is the following issue: https://github.com/nodejs/docker-node/issues/1335. As already mentioned at the top of the Node.js issue, a possible solution would be to run it in offline mode, i.e. to cache the packages.
I have now adapted the GitHub workflow file so that it already works.
As you have already correctly noted, I have added QEMU.
Since this problem only affects Node, the backend is not affected and already has the multi-architecture variant. To give the frontend multi-arch as well, you would only have to add `linux/arm64` to the platform, and then it should also work there.
But I still have a question: Why do you not work with the versions in the workflow file, …
> fix: publish docker image workflow

- docker-compose.yml
- docs/docs/deployment/docker.md
Fixes issue where containers cannot to talk to each other where the default docker network is isolated.
> Feat: added volume, network and port to docker compose

- backend/bracket/logic/ranking/calculation.py
- backend/bracket/logic/ranking/elimination.py
- backend/bracket/logic/scheduling/builder.py
- backend/bracket/logic/scheduling/handle_stage_activation.py
- backend/bracket/models/db/match.py
- backend/bracket/routes/matches.py
- backend/bracket/routes/rankings.py
- backend/bracket/routes/rounds.py
- backend/bracket/routes/stage_items.py
- backend/bracket/routes/util.py
- backend/bracket/sql/matches.py
- backend/bracket/sql/rounds.py
- backend/bracket/sql/stage_items.py
- backend/bracket/utils/db_init.py
- backend/tests/integration_tests/api/stage_items_test.py
- backend/tests/unit_tests/elimination_test.py
- backend/tests/unit_tests/ranking_calculation_test.py
- frontend/src/components/brackets/match.tsx
- frontend/src/components/modals/create_stage_item.tsx
- frontend/src/components/modals/match_modal.tsx
- frontend/src/interfaces/match.tsx
- frontend/src/pages/tournaments/[id]/dashboard/index.tsx
- frontend/src/pages/tournaments/[id]/results.tsx
- frontend/src/pages/tournaments/[id]/schedule.tsx
fixes https://github.com/evroon/bracket/issues/998
> Assign teams to subsequent elimination rounds

- frontend/src/components/modals/team_update_modal.tsx
Team logos currently do not load because the URL does not reflect the location of team logos. This should fix it
> Fix Team Logos not loading

- backend/Dockerfile
- docker-compose.yml
- frontend/Dockerfile
ref https://github.com/evroon/bracket/issues/1150
the backend healthcheck on localhost doesn't work, needs to be `0.0.0.0`:
```
/app $ wget --spider http://localhost:8400/ping
Connecting to localhost:8400 ([::1]:8400)
wget: can't connect to remote host: Connection refused
```
> Fix healthcheck commands

- frontend/Dockerfile
This PR fixes the entrypoint `sed` error:
```
bracket-frontend  | sed: can't create temp file 'public/locales/ja/common.jsonXXXXXX': Permission denied
bracket-frontend  | sed: can't create temp file 'public/locales/it/common.jsonXXXXXX': Permission denied
bracket-frontend  | sed: can't create temp file 'public/locales/nl/common.jsonXXXXXX': Permission denied
bracket-frontend  | sed: can't create temp file 'public/favicon-wide.svgXXXXXX': Permission denied
bracket-frontend  | sed: can't create temp file 'public/favicon.svgXXXXXX': Permission denied
```
The public folder is now owned by `nextjs:nodejs`.
> fix sed error

- frontend/next-i18next.config.js
I was wondering why these locale were not added in the project. Adding them make the language configuration UI works properly with missing languages. Right now, if you set french or italian, it does not work. With this patch, everything works out.
> add missing locale

- frontend/src/components/info/player_list.tsx
Hi there, cool project. I appreciated seeing a working example of FastAPI + NextJS together.
I noticed the teams table didn't show each team member in the members column, so here's a small PR to do so. Feel free to suggest edits!
Screenshot:
> Add member names to teams table

- docs/content/deployment/index.mdx
I noticed another broken link while using the docs.
> Fix link to config docs from deployment page

- docs/content/community/development.mdx
- docs/content/deployment/index.mdx
- process-compose-example.yml
Fix a broken link in `docs/content/deployment/index.mdx`, make all links absolute for clarity and fix the command to start docs in process-compose-example.yml
> Fix process compose docs cmd and broken link

- backend/bracket/logic/planning/matches.py
This PR alters the match scheduling logic
Now, the algorithm schedules all matches for each stage in sequence (i.e. all matches from stage A, then all matches from stage B). Matches from stage items inside a single stage are interleaved.
To guarantee that the correct order is followed, rounds are sorted according to their id. Lower round id are scheduled first.
Fix #1312
> Fix match sorting algorithm
